server:
  port: 9100

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8181/
          predicates:
            - Path= /auth/**
          filters:
            - AuthenticationFilter
            - RewritePath= /auth/(?<path>.*), /$\{path}
        - id: broker
          uri: http://localhost:7000/
          predicates:
            - Path= /broker/**
            #- Path= /lease/**
          filters:
            - AuthenticationFilter
            - RewritePath=/broker/(?<path>.*), /$\{path}
        - id: inventory
          uri: http://localhost:7001/
          #uri: lb://inventory
          predicates:
            - Path= /inventory/**
          filters:
            - AuthenticationFilter
            - RewritePath=/inventory/(?<path>.*), /$\{path}
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


jwt:
  secret: secretkey
  token.validity: 900000
  authDisabled: true